### ISSUE TITLE
Add compatibility with ncchinfo.bin generated by Riku's 3DS Simple CIA Converter

### ISSUE THREAD

**Issue by zeruel85** [archshift/Decrypt9#41] opened 2015-08-27 08:06 UTC
Like the title says... I have a N3DS with your very useful tool, Decrypt9, but if I generate the ncchinfo.bin from 3DS Simple CIA Converter by Riku (IMHO the best, easy and quick converter actually available), it does not work. Riku's ncchinfo.bin works flawlessly with rxTools and its Xorpads generator tool. May I ask if you can add the compatibility too? Thank you in advance and congrats for this precious tool. :)

**Comment by Syphurith** [comment] 2015-08-29 05:49
@zeruel85 Even i'm not from the team please let me answer you a bit.
_Note: For some devs this issue looks noob, and for some other it looks related too much to piracy and the else is just too busy. Hope question is not too noob so they wouldn't get tired to see your issue._
The incompatibility is caused by string encoding. Decrypt9 itself generates UTF-16 one (in its `scripts/ncchinfo_gen.py`). Most CIA convertors uses UTF-8, and is the same for rxTools, or even more.
For characters in UTF-16 every char takes 2 bytes, `0` would stands for `00 30` in binary. on the other hand, UTF-8 is an encoding with variable length. it may takes you only 1 byte for ASCII but not the same for CJK or chars from other region. This makes UTF-16 eaiser to be dealt than UTF-8.
Now you have several choices to do your deed.
- **Write a simple script to convert the ncchinfo.bin back and forth.** When it takes in UTF-8 encoded one get it converted to UTF-16 and vice versa. Not difficult at all, you could use different tools to generate the bin and take a look with any Hex editors. Once you have a good written script you could hand it to the author of convertor so he could make it much eaiser to use.
- **Just use the script included in decypt9 to generate the bin, so no compatibility issue.** Xorpads looks the same. Always use which script decyptor offers to you to get the best compatibility. convertor itself couldn't generates xorpads for you, the KEY is not found. So whichever tool you use it would always ask you for the xorpads, and you could generate it totally with decrypt9 or other.
- **Modify the source code and let it done with ASCII or UTF-8.** I would like to warn you that UTF-8 interpreter isn't ever easy to be implemented, you would have to restrict it to ASCII. Luckily most scripts for the ncchinfo.bin i've seen doesn't use the filename it takes in. **Not recommended.**

Hope your issue get well and easily solved. Best wishes to the devs and you.

**Comment by zeruel85** [comment] 2015-08-31 06:58
Ok, thank you for your hints. I'll try to find out the smartest way to do what you've written at point 1 of 3. :)

**Comment by d0k3** [comment] 2015-10-24 16:44
Already fixed in this commit:
https://github.com/archshift/Decrypt9/commit/cb196a78a85e11ab4c6eda33f582671cb44cd63f
Decrypt9 will now also process ncchinfo.bin generated by Rikus converter.

This can be closed!

**Comment by Syphurith** [comment] 2015-10-25 03:15
Thanks. That's good news to hear, @d0k3. _Eh, readed this commit log, i wonder if there is really something must be decrypted on new 3ds.. Is that not sufficient even he has some leaked keys?_
~~_BTW, i had a crazy idea. I doubt if part of the decrypted NAND image could be solid content, could the xorpad generation be reversed to cover a part of it to a full xorpad?_~~

**Closed as completed** 2015-10-25 06:49 UTC
